apiVersion: apps/v1
kind: Deployment
metadata:
  name: managedcluster-import-controller
  namespace: open-cluster-management
  labels:
    app: managedcluster-import-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: managedcluster-import-controller
  template:
    metadata:
      labels:
        name: managedcluster-import-controller
    spec:
      serviceAccountName: managedcluster-import-controller
      containers:
        - name: managedcluster-import-controller
          image: REPLACE_IMAGE
          imagePullPolicy: Always
          command: 
          - managedcluster-import-controller
          env:
            - name: WATCH_NAMESPACE
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "managedcluster-import-controller"
            - name: DEFAULT_IMAGE_PULL_SECRET
              value: multiclusterhub-operator-pull-secret
            - name: DEFAULT_IMAGE_REGISTRY
              value: quay.io/open-cluster-management
            - name: REGISTRATION_OPERATOR_IMAGE
              value: quay.io/open-cluster-management/registration:latest
            - name: WORK_OPERATOR_IMAGE
              value: quay.io/open-cluster-management/work:latest
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
